version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "rm -f /healthapp/tmp/pids/server.pid &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./backend:/healthapp
      - ./backend/vendor/bundle:/healthapp/vendor/bundle
    environment:
      RAILS_ENV: development
    ports:
      - 8000:3000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd app && yarn start"
    ports:
      - "3000:3000"
volumes:
  postgres-data:
    driver: local